baseURL = "https://chrisleggett.me/"
languageCode = "en-us"
title = "Christopher Leggett"
theme = "lenora"
disqusShortname = "chrisleggett-me"

[markup]
    [markup.highlight]
    style = "monokailight"

[build]
writeStats=true
